api_login_check:
    path: /api/login_check

gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken:refresh

app:
    resource: ../src/Controller/
    type: rest

fos_user_registration_confirm:
    path: /confirmation
    host: localhost